version: '4.62'
services:
  playwright-test:
    image: playwrighttest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run test
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results
